version: "2"
run:
  relative-path-mode: gomod
  go: ""
  tests: true
  allow-parallel-runners: false
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - govet
    - iface
    - ineffassign
    - lll
    - mirror
    - nestif
    - nilnesserr
    - nolintlint
    - nosprintfhostport
    - reassign
    - recvcheck
    - revive
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    depguard:
      rules:
        main:
          files:
            - '**/*.go'
          deny:
            - pkg: github.com/stretchr/testify
              desc: Use stdlib for testing purposes
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
    govet:
      enable-all: true
    lll:
      line-length: 120
      tab-width: 8
    nestif:
      min-complexity: 6
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/generated
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: weezel/example-gin
  exclusions:
    generated: lax
    paths:
      - pkg/generated
