run:
  timeout: 3m
  go: "" # empty -> will be read from go.mod file instead
  skip-dirs:
    # Directory has generated code
    - pkg/generated
  # Also lint tests
  tests: true
  # When enabled these are skipped:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: false
  allow-parallel-runners: false
  concurrency: 2
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  govet:
    check-shadowing: true
    enable-all: true
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and
    # can be changed with the tab-width option.
    # Default: 120.
    line-length: 120
    # Tab width in spaces.
    # Default: 1
    tab-width: 8
  depguard:
    rules:
      main:
        files:
          - "**/*.go"
        deny:
          - pkg: "github.com/stretchr/testify"
            desc: "Use stdlib for testing purposes"
linters:
  disable-all: true
  enable:
    - bodyclose
    - contextcheck
    - depguard
    - dupl
    - durationcheck
    - errcheck # default
    - errorlint
    - exhaustive
    - exportloopref
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple # default
    - govet # default
    - ineffassign # default
    - lll
    - nolintlint
    - revive
    - sqlclosecheck
    - staticcheck # default
    - typecheck # default
    - unconvert
    - unused # default
    - usestdlibvars
# issues:
output:
  # Sort results by: filepath, line and column.
  sort-results: true

issues:
  # Show all the results, don't hide anything
  max-issues-per-linter: 0
  max-same-issues: 0
