run:
  timeout: 3m
  go: "1.20"
  skip-dirs:
    # Directory has generated code
    - pkg/generated
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  govet:
    check-shadowing: true
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and
    # can be changed with the tab-width option.
    # Default: 120.
    line-length: 120
    # Tab width in spaces.
    # Default: 1
    tab-width: 8
  depguard:
    additional-guards:
      - list-type: denylist
        include-go-root: false
        packages:
          - github.com/stretchr/testify
linters:
  enable:
    - contextcheck
    - deadcode
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - lll
    - maligned
    - revive
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
issues:
output:
  # Sort results by: filepath, line and column.
  sort-results: true
