services:
  postgres:
    image: "postgres:14.4"
    restart: on-failure:3
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    command: "-c log_statement=all"
    # Uncomment the following lines to retain the data
    #volumes:
    #  - "$PWD/postgres-data:/var/lib/postgresql/data:rw"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
     - "127.0.0.1:14250:14250"
     - "127.0.0.1:14268:14268"
     - "127.0.0.1:16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
