services:
  postgres:
    image: "postgres:17.2"
    restart: on-failure:3
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    command: "-c log_statement=all"
    # Uncomment the following lines to retain the data
    #volumes:
    #  - "$PWD/postgres-data:/var/lib/postgresql/data:rw"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.118.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686
