name: Linting and static code analysis

permissions: {} # no need any permissions

on:
  push:
    branches: [cicd-test]
  pull_request:
    branches: [cicd-test]
  workflow_call:

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Copy sql files to dbmgirate directory for embed usage
        shell: bash
        run: "cp -R sql/schemas cmd/dbmigrate/"
        working-directory: "."

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m
          working-directory: "."
